os: linux
dist: xenial

sudo: required

addons:
  apt:
    packages:
      - cpanminus
      - build-essential
      - libncurses5-dev
      - libpcre3-dev
      - libreadline-dev
      - libssl-dev
      - perl
      - luarocks

env:
  global:
    - JOBS=1
    - OPENRESTY_PREFIX=/usr/local/openresty

before_install:
  - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install openresty
  - git clone https://github.com/openresty/test-nginx.git test-nginx

script:
  - export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
  - make compile > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make deps > build.log 2>&1 || (cat build.log && exit 1)
  - prove -Itest-nginx/lib -r t
