name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: "ubuntu-18.04"
    env:
      OPENRESTY_PREFIX: "/usr/local/openresty"

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Linux Get dependencies
        run: |
          sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl lua5.1 liblua5.1-0-dev
          curl -fsSL https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh | sh
      - name: Linux Before install
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

      - name: Linux Install
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty
          git clone https://github.com/openresty/test-nginx.git test-nginx


      - name: Linux Script
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          make compile > build.log 2>&1 || (cat build.log && exit 1)
          sudo make deps > build.log 2>&1 || (cat build.log && exit 1)
          prove -Itest-nginx/lib -I. -r t
